aivf/blueprints/user/views.py
from flask import Blueprint, request, flash, redirect, url_for, render_template
from flask_login import login_required, login_user, logout_user

from lib.safe_next_url import safe_next_url

from aivf.blueprints.user.decorators import anonymous_required
from aivf.blueprints.user.forms import LoginForm
from aivf.blueprints.user.models import User

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/login', methods=['GET', 'POST'])
@anonymous_required()
def login():
    form = LoginForm(next=request.args.get('next'))

    if form.validate_on_submit():

        try:
            u = User.objects.get(email=request.form.get('identity'))
        except User.DoesNotExist:
            u = None

        if u and u.authenticated(False, request.form.get('password')):
            if login_user(u, remember=True):
                #  u.update_activity_tracking(request.remote_addr)

                next_url = request.form.get('next')
                if next_url:
                    return redirect(safe_next_url(next_url))
                #  return redirect(url_for('user.settings'))
                return redirect("/")
        else:
            flash('Identity or password is incorect.', 'error')

    return render_template('user/login.html', form=form)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('user.login'))

aivf/templates/layouts/base.html
{% import 'macros/flash.html' as flash with context %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet"
        href="/static/styles/vendor/bootstrap.min.css">
  <script src="https://kit.fontawesome.com/670f54f3ad.js"
          crossorigin="anonymous"></script>
  <title>{% block title %}{% endblock %}</title>
</head>

<body>

  <main class="container mb-5">
    {% include "layouts/navbar.html" %}
    {{ flash.render() }}
    {% block body %}{% endblock %}
  </main>

  <script src="/static/scripts/vendor/jquery-3.3.1.slim.min.js"></script>
  <script src="/static/scripts/vendor/popper.min.js"></script>
  <script src="/static/scripts/vendor/bootstrap.min.js"></script>
</body>

</html>

aivf/templates/layouts/navbar.html
<nav class="navbar navbar-expand-sm navbar-light bg-light mb-4">
  <a class="navbar-brand"
     href="/"><i class="fas fa-microscope"></i>&nbsp;AIVF</a>
  <button class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse"
       id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link"
           href="/">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link"
           href="/patient/query">Query Patient</a>
      </li>
    </ul>
    <ul class="navbar-nav my-2 my-lg-0">
      {% if current_user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           data-toggle="dropdown"
           role="button"
           aria-haspopup="true"
           aria-expanded="false"
           href="">
          <i class="fas fa-user"></i>&nbsp;{{ current_user.name }}
          <span class="caret"></span>
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item"
             href="{{ url_for('user.logout') }}">
            Log out
          </a>
        </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link"
           href="{{ url_for('user.login') }}">
          <i class="fas fa-sign-in-alt"></i>&nbsp;Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>